apiVersion: v1
kind: Service
metadata:
  name: weather-info-service
spec:
  type: NodePort
  selector:
    app: weather-info
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
