name: Docker Cron Job

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  docker-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker is working
        run: docker version

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container (optional)
        run: docker run -d -p 3000:3000 my-app

      # Optional cleanup
      # - name: Stop container
      #   run: docker stop $(docker ps -q)


